---
# install tasks for apache2

- name: apache2 | package | install
  package:
    name: "{{ apache2_package_name }}"
    state: present

- name: apache2 | package | install modules
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache2_module_packages }}"
