---
# pre install tasks for apache2 role


# Create unpriv user/group to own apache worker threads.

- name: apache2 | group | create
  group:
    name: "{{ apache2_group_name }}"
    state: present
    system: true

- name: apache2 | user | create
  user:
    name: "{{ apache2_user_name }}"
    state: present
    system: true
    comment: Unprivileged user for apache2/httpd server
    group: "{{ apache2_group_name }}"
    shell: /sbin/nologin
    home: "{{ apache2_user_home }}"


