---
# tasks for creating and enabling vhosts for apache2

- name: apache2 | vhost | create document root
  file:
    name: "{{ item.document_root | default([apache2_content_root, item.domain | default(item.name)] | join('/')) }}"
    state: directory
    owner: root
    group: "{{ apache2_group_name }}"
    mode: "01750"


- name: apache2 | vhost | create ssl directory
  file:
    name: "{{ apache2_ssl_root }}/{{ item.domain | default(item.name) }}/"
    state: directory
    owner: root
    group: root
    mode: "01710"
  when: not item.cert | default(false, true)

- name: apache2 | vhost | create self-signed certificate
  command: "/usr/bin/openssl req -x509 -newkey rsa:2048 -nodes -keyout key.pem -subj '/CN={{ item.domain | default(item.name) }}' -out chain.pem"
  args:
    creates: "{{ apache2_ssl_root }}/{{ item.domain | default(item.name) }}/key.pem"
    chdir: "{{ apache2_ssl_root }}/{{ item.domain | default(item.name) }}/"
  when: not item.cert | default(false, true)

- name: apache2 | vhost | create log directory
  file:
    name: "{{ apache2_log_root }}/{{ item.name }}/"
    state: directory
    owner: root
    group: "{{ apache2_group_name }}"
    # Allow apache group wx, but not reading.
    # It may be preferrable to have the apache user own the dir (mode 350),
    # and have a group able to read logs...
    mode: "01730"

- name: apache2 | vhost | create {{ item.name }} configuration
  template:
    src: "{{ item.source_template | default('simple_vhost.conf.j2') }}"
    dest: "/etc/{{ apache2_service_name }}/sites-available/{{ item.name }}.conf"
    owner: root
    group: "{{ apache2_group_name }}"
    mode: "0640"
  notify: apache2 | service | restart

- name: apache2 | configuration | enable vhost {{ item.name }}
  file:
    src: "/etc/{{ apache2_service_name }}/sites-available/{{ item.name }}.conf"
    dest: "/etc/{{ apache2_service_name }}/sites-enabled/{{ item.name }}.conf"
    state: link
    owner: root
    group: "{{ apache2_group_name }}"
  when: item.enabled | default(true)
  notify: apache2 | service | restart
