---
# run tasks for dnscrypt-proxy

- name: dnscrypt-proxy | run | create systemd service unit
  template:
    src: dnscrypt-proxy.service.j2
    dest: "/etc/systemd/system/{{ dnscrypt_proxy_service_name }}.service"
    owner: root
    group: root
    mode: "0640"

- name: dnscrypt-proxy | run | enable and start main service
  service:
    name: "{{ dnscrypt_proxy_service_name }}"
    state: started
    enabled: yes
