---
# defaults file for prometheus

# Version of the prometheus binary or docker container to use.
# For docker containers, if the version is \d+.\d+.\d+, a v will be prepended.
prometheus_version: "2.0.0"

# Port to have prometheus list for web requests on
# If prometheus is dockerised, this is the port exposed by the container
prometheus_ports:
  - 9090

# Whether to publish the prometheus ports.
# If not falsy, it needs to be a suitable portspec.
# In other words, to publish prometheus port, you would have:
# prometheus_docker_publish_ports:
#   - 9090:9090
prometheus_docker_publish_ports: no

# Whether to run prometheus as a system service.
# Default is to do so, unless running in a docker container.
# This will be ignored if run_dockerised is truthy.
prometheus_run_services: not (ansible_virtualization_role == 'guest' and ansible_virtualization_type == 'docker')

# Whether to run prometheus in a docker container
prometheus_run_dockerised: no

# Image to use to run prometheus.
prometheus_docker_image: prom/prometheus

# Networks prometheus should be part of
prometheus_docker_networks:
  - name: bridge

# Devices/volumes to expose to the container.
prometheus_docker_volumes:
  - /etc/prometheus:/etc/prometheus/:ro,Z

# Platform to download binary for.
prometheus_platform: "{{ 'darwin' if ansible_os_family == 'Darwin' else 'linux' }}"

# Architecture to download binary for.
prometheus_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

prometheus_alertmanagers: []
prometheus_alertmanager_group: "prometheus_alertmanagers"

# Blackbox exporter to use for default blackbox_exporter profile
prometheus_blackbox_address: "127.0.0.1:9115"

prometheus_default_scrape_configs:
  blackbox_exporter:
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "{{ prometheus_blackbox_address }}"



# Per type scrape configs, primarily used to configure the blackbox_exporter.
# The types are whatever is used in prometheus_scrape_targets for the type value.
prometheus_scrape_configs: "{{ prometheus_default_scrape_configs }}"

# Alert relabelling configuration
prometheus_alert_relabeling: []

# Define scrape targets.
# Each target is used to populate scraped_targets.json.j2
#
prometheus_default_scrape_targets:
  - name: prometheus_local
    type: prometheus
    port: 9090
    targets:
      - "{{ inventory_hostname }}:9090"
  - name: ansible_node_exporters
    type: node_exporter
    port: 9100
    groups:
      - node_exporter
  - name: docker
    type: docker
    port: 9323
    groups:
      - docker
  - name: public_sites
    type: blackbox_exporter
    targets:
      - https://google.com
      - https://en.wikipedia.org
      - https://cloudflare.com
  - name: haproxy
    type: haproxy
    port: 9101
    groups:
      - haproxy
  - name: grafana
    type: grafana
    port: 3000
    groups:
      - grafana


prometheus_scrape_targets: "{{ prometheus_default_scrape_targets }}"
