---
# defaults file for prometheus

# Version of the prometheus binary or docker container to use.
# For docker containers, if the version is \d+.\d+.\d+, a v will be prepended.
prometheus_version: "1.8.0"

# Port to have prometheus list for web requests on
# If prometheus is dockerised, this is the port exposed by the container
prometheus_ports:
  - 9090

# Whether to publish the prometheus ports.
# If not falsy, it needs to be a suitable portspec.
# In other words, to publish prometheus port, you would have:
# prometheus_docker_publish_ports:
#   - 9090:9090
prometheus_docker_publish_ports: no

# Whether to run prometheus as a system service.
# Default is to do so, unless running in a docker container.
# This will be ignored if run_dockerised is truthy.
prometheus_run_services: not (ansible_virtualization_role == 'guest' and ansible_virtualization_type == 'docker')

# Whether to run prometheus in a docker container
prometheus_run_dockerised: no

# Image to use to run prometheus.
prometheus_docker_image: prom/prometheus

# Networks prometheus should be part of
prometheus_docker_networks:
  - name: bridge

# Devices/volumes to expose to the container.
prometheus_docker_volumes:
  - /etc/prometheus:/etc/prometheus/:ro,Z

# Platform to download binary for.
prometheus_platform: "{{ 'darwin' if ansible_os_family == 'Darwin' else 'linux' }}"


prometheus_scrape_targets:
  - name: prometheus_local
    type: prometheus
    port: 9090
    targets:
      - "{{ inventory_hostname }}:9090"
  - name: ansible_node_exporters
    type: node_exporter
    port: 9100
    groups:
      - node_exporter
  - name: docker
    type: docker
    port: 9323
    groups:
      - docker
  - name: haproxy
    type: haproxy
    port: 9101
    groups:
      - haproxy

