---

# install tasks for nodejs

- name: nodejs | install | packages
  package:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ nodejs_package_names }}"

- name: nodejs | install | n
  npm:
    name: "{{ item }}"
    state: "present"
    global: true
    production: true
  with_items:
    - inherits
    - n
  when: nodejs_install_n | default(false, true)

- name: nodejs | install | node version
  command: "n {{ nodejs_version }}"
  when: nodejs_install_n | default(false, true)
