---
# tasks file for ossec-server


- block:
    - include_tasks: install.yml
      tags:
        - install
    - include_tasks: configure.yml
      tags:
        - configure
    - include_tasks: run.yml
      tags:
        - run
  tags:
    - ossec
    - ossec-server
