---

- name: nginx | configure | selinux booleans
  seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true


- name: nginx | configuration | nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: nginx
    mode: "0640"
    validate: /usr/sbin/nginx -t -c %s
  notify:
    - nginx | service | restart


- name: nginx | configuration | create directories
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: nginx
    mode: "0640"
  with_items:
    - /etc/nginx/sites-enabled/
    - /etc/nginx/sites-available/

- include_tasks: vhost.yml
  with_items: "{{ nginx_vhosts }}"
  loop_control:
    loop_var: vhost
