---
# pre-install tasks for nginx

- name: nginx | group | create
  group:
    name: "{{ nginx_group_name }}"
    state: present
    system: true

- name: nginx | user | create
  user:
    name: "{{ nginx_user_name }}"
    group: "{{ nginx_group_name }}"
    state: present
    system: true
    home: /var/lib/nginx
    shell: /sbin/nologin
    createhome: false

- name: nginx | homedir | create
  file:
    name: /var/lib/nginx
    state: directory
    owner: "{{ nginx_user_name }}"
    group: "{{ nginx_group_name }}"
    mode: "01750"


