---

# pre-install tasks for unbound

- name: unbound | create | group
  group:
    name: unbound
    state: present
    system: true

- name: unbound | create | user
  user:
    name: unbound
    state: present
    group: unbound
    shell: /sbin/nologin
    system: true
    home: /var/lib/unbound
    skeleton: /dev/null

- name: unbound | create | configuration directories
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: unbound
    mode: "0750"
  with_items:
    - /etc/unbound

