---
# tasks file for openvas

- block:
    - include_tasks: pre_install.yml
      tags:
        - pre_install
    - include_tasks: install.yml
      tags:
        - install
    - include_tasks: configure.yml
      tags:
        - configure
    - include_tasks: bootstrap.yml
      tags:
        - bootstrap
    - include_tasks: run.yml
      tags:
        - run
  tags:
    - openvas
