---
# tasks file for configuring docker

- name: docker | configuration | create directory
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "1750"
  with_items:
    - "{{ docker_config_dir }}"
    - "{{ docker_config_dir }}/ssl"

- name: "docker | configuration | create daemon.json"
  copy:
    dest: "{{ docker_config_dir }}/daemon.json"
    content: "{{ docker_config | to_json() }}"
    owner: root
    group: "{{ docker_group }}"
    mode: "0640"

- name: docker | configuration | create sysconfig file
  copy:
    dest: "{{ docker_environment_file }}"
    content: "DOCKER_OPTS='--config-file {{ docker_config_dir }}/daemon.json --group {{ docker_group }}'\n"
    owner: root
    group: root
    mode: "0640"

- name: docker | configuration | create system service drop-in directory
  file:
    name: /etc/systemd/system/{{ docker_service_name }}.service.d/
    state: directory
    owner: root
    group: root
    mode: "01750"
  when: "ansible_service_mgr == 'systemd'"
