---
# configuration tasks for suricata

- name: suricata | rules | configure ET rules updater
  template:
    src: systemd.suricata-et-rules.service.j2
    dest: /etc/systemd/system/suricata-et-rules.service
    owner: root
    group: root
    mode: "0600"
  tags:
    - ids
    - suricata
    - et-open-rules

- name: suricata | rules | configure ET rules update timer
  template:
    src: systemd.suricata.timer.j2
    dest: /etc/systemd/system/suricata-et-rules.timer
    owner: root
    group: root
    mode: "0600"
  tags:
    - ids
    - suricata
    - et-open-rules

- name: suricata | config | create
  template:
    src: suricata.yaml.j2
    dest: /etc/suricata/suricata.yaml
    owner: root
    group: root
    mode: "0600"
  tags:
    - ids
    - suricata
