---
# run tasks for suricata

- name: suricata | service | enable rule refresh units
  service:
    name: suricata-et-rules
    state: stopped
    enabled: yes
  tags:
    - service

- name: suricata | service | run
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - suricata
    - suricata-et-rules.timer
  tags:
    - service
