---
# Tasks for configuring grafana

- name: grafana | configuration | create env file
  template:
    src: grafana-server.env.j2
    dest: /etc/sysconfig/grafana-server
    owner: root
    group: grafana
    mode: "0640"


- name: grafana | configuration | create service unit
  template:
    src: grafana-server.service.j2
    dest: /etc/systemd/system/grafana-server.service
    owner: root
    group: root
    mode: "0640"
  when: ansible_service_mgr == 'systemd'

- name: grafana | configuration | create grafana.ini
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: "0640"
