---
# tasks file for grafana

- block:
    - import_tasks: pre_install.yml
    - import_tasks: install.yml
    - import_tasks: configure.yml
    - import_tasks: run.yml
    - import_tasks: api.yml
      when: grafana_data_sources | length
  tags:
    - grafana
