---
# pre install tasks for grafana

- name: grafana | group | create
  group:
    name: grafana
    state: present
    system: yes

- name: grafana | user | create
  user:
    name: grafana
    state: present
    group: grafana
    home: /usr/share/grafana
    shell: /sbin/nologin
    expires: -1
    system: yes

- name: grafana | directories | create
  file:
    name: "{{ item }}"
    state: directory
    owner: grafana
    group: grafana
    mode: "01750"
  with_items:
    - /etc/grafana
    - /var/log/grafana
    - /var/lib/grafana

- name: grafana | repository | add
  yum_repository:
    name: "grafana"
    state: present
    description: "Grafana repository"
    baseurl: "{{ grafana_repository_url }}"
    gpgkey: https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
    gpgcheck: yes
    enabled: yes
    sslverify: yes
    includepkgs: "grafana grafana-server"
  when: ansible_pkg_mgr == 'yum'
  register: grafana_add_repo

- name: grafana | yum | download and accept gpg keys
  command: yum makecache fast -y
  when: grafana_add_repo.changed
