---
# tasks file for auditd

- name: audit | config | create directories
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "01750"
  with_items:
    - /etc/audit
    - /etc/audit/rules.d

- name: audit | package | install
  package:
    name: audit
    state: present

- include: ruleset.yml

- name: audit | service | enable and start
  service:
    name: auditd
    state: started
    enabled: yes
  when: auditd_run_services
