--- 

# Install any client packages that may be required.
- name: openssh | client | install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ openssh_client_packages }}"
  tags:
    - ssh_client

# Manage SSH client config
- name: openssh | client | create ssh_config
  template:
    dest: /etc/ssh/ssh_config
    src: ssh_config.j2
    owner: root
    group: root
    mode: "0644"
  tags:
    - ssh_client
