---

# configuration tasks for openssh

# Generate server host keys
- name: openssh | server | generate host keys
  command: /usr/bin/ssh-keygen -A
  args:
    creates: "{{ openssh_config_dir }}/ssh_host_*_key"
  when: "not openssh_skip_server"
  tags:
    - key_generation


# Manage SSH server config
- name: openssh | server | create sshd_config
  template:
    dest: /etc/ssh/sshd_config
    src: sshd_config.j2
    owner: root
    group: root
    mode: "0600"
    validate: /usr/sbin/sshd -t -f %s
  notify:
    - openssh | server | restart service
  when: "not openssh_skip_server"
  tags:
    - ssh_server



- name: openssh | server | create additional config folders
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0751"
  when: "not openssh_skip_server"
  with_items:
    - /etc/ssh/user_authorized_keys


# Create trusted user ca file
- name: openssh | server | create trusted_user_ca_keys.pub
  copy:
    dest: "/etc/ssh/trusted_user_ca_keys.pub"
    owner: root
    group: root
    mode: "0644"
    content: |
        {% for key in openssh_server_user_ca_keys %}
        {{ key }}
        {% endfor %}
  when: "not openssh_skip_server"
  notify:
    - openssh | server | restart service


# Create revoked key file
- name: openssh | server | create revoked_keys.pub
  copy:
    dest: "/etc/ssh/revoked_keys.pub"
    owner: root
    group: root
    mode: "0644"
    content: |
        {% for key in openssh_server_revoked_keys %}
        {{ key }}
        {% endfor %}
  when: "not openssh_skip_server"
  notify:
    - openssh | server | restart service


# Manage SSH client config
- name: openssh | client | create ssh_config
  template:
    dest: /etc/ssh/ssh_config
    src: ssh_config.j2
    owner: root
    group: root
    mode: "0644"
  when: "not openssh_skip_client"

