---
# tasks file for openssh

# Include OS-specific variable files
- name: openssh | variables | OS specific variables
  include_vars:
    file: "{{ ansible_os_family | lower }}.yml"
  ignore_errors: True
  tags:
    - ssh
    - openssh

- block:
    - import_tasks: pre_install.yaml
    - import_tasks: install.yaml
    - import_tasks: configure.yaml
    - import_tasks: run.yaml
  tags:
    - ssh
    - openssh
