---
# tasks file for common

- block:
    - import_tasks: yum.yml
      tags:
        - yum
      when: ansible_pkg_mgr == 'yum'
    - import_tasks: packages.yaml
      tags:
        - common-packages
  tags:
    - common
