---
# tasks file for weave-net

- block:
    - import_tasks: pre_install.yaml
    - import_tasks: install.yaml
    - import_tasks: configure.yaml
    - import_tasks: run.yaml
  tags:
    - weave-net
    - docker-networking
