---

# run tasks for weave-net

- name: weave-net | run | create service unit
  template:
    src: weave-net.service.j2
    dest: "/etc/systemd/system/{{ weave_net_service_name }}.service"
    owner: root
    group: root
    mode: "0640"
  notify:
    - weave-net | restart | service

- name: weave-net | run | start and enable service
  service:
    name: "{{ weave_net_service_name }}"
    state: started
    enabled: true
