---
# configuration tasks for etcd

- name: etcd | configuration | create base
  template:
    src: etcd.yaml.j2
    dest: "/etc/etcd/conf.d/{{ etcd_node_name }}.yaml"
    owner: root
    group: etcd
    mode: "0640"
  notify:
    - etcd | service | restart

- name: etcd | configuration | create env
  copy:
    dest: "/etc/etcd/env.d/{{ etcd_node_name }}.env"
    content: |
      {{ etcd_service_env }}
    owner: root
    group: etcd
    mode: "0640"
  notify:
    - etcd | service | restart

- name: etcd | service | create configuration
  template:
    src: etcd.service.j2
    dest: "/etc/systemd/system/{{ etcd_service_name }}.service"
    owner: root
    group: root
    mode: "0640"

