---
# tasks file for etcd

- block:
    - import_tasks: pre_install.yml
    - import_tasks: install.yml
    - import_tasks: configure.yml
    - import_tasks: run.yml
    - import_tasks: consul.yaml
      when: etcd_announce_consul
  tags:
    - etcd
