---
# tasks for configuring prometheus node_exporter

- name: prometheus blackbox exporter | config | create directory
  file:
    name: /etc/prometheus_blackbox_exporter
    state: directory
    owner: root
    group: prometheus
    mode: "01750"

- name: prometheus blackbox exporter | config | create blackbox.yml
  template:
    src: blackbox.yml.j2
    dest: /etc/prometheus_blackbox_exporter/blackbox.yml
    owner: root
    group: prometheus
    mode: "0640"

- name: prometheus | environment | create env file for systemd unit
  copy:
    dest: /etc/prometheus_blackbox_exporter/blackbox_exporter.env
    content: OPTIONS=""
    owner: root
    group: prometheus
    mode: "0640"
    force: no
