---
# tasks file for prometheus_blackbox_exporter

- import_tasks: pre_install.yml
  when: not prometheus_blackbox_run_dockerised
  tags:
    - prometheus
    - blackbox_exporter

- import_tasks: install.yml
  when: not prometheus_blackbox_run_dockerised
  tags:
    - prometheus
    - blackbox_exporter

- import_tasks: configure.yml
  tags:
    - prometheus
    - blackbox_exporter

- import_tasks: run.yml
  tags:
    - prometheus
    - blackbox_exporter
