---
# tasks file for prometheus_blackbox_exporter

- include: pre_install.yml
  when: not prometheus_blackbox_run_dockerised

- include: install.yml
  when: not prometheus_blackbox_run_dockerised

- include: configure.yml

- include: run.yml
