---
# Tasks for running prometheus node-exporter

- name: prometheus_blackbox_exporter | systemd | create service unit
  template:
    src: prometheus_blackbox_exporter.service.j2
    dest: /etc/systemd/system/prometheus_blackbox_exporter.service
    owner: root
    group: root
    mode: "0640"
  when: ansible_service_mgr == 'systemd' and not prometheus_blackbox_run_dockerised


- name: prometheus_blackbox_exporter | service | start and enable
  service:
    name: prometheus_blackbox_exporter.service
    state: started
    enabled: yes
  when: "prometheus_blackbox_run_services and not prometheus_blackbox_run_dockerised"

- name: prometheus_blackbox_exporter | docker | run container
  docker_container:
    name: "{{prometheus_blackbox_container_name}}"
    state: started
    image: "{{ prometheus_blackbox_docker_image }}:{{ prometheus_blackbox_version | regex_replace('^(\\d+\\.\\d+\\.\\d+)$','v\\1') }}"
    command: "--config.file=/config/blackbox.yml"
    networks: "{{ prometheus_blackbox_docker_networks }}"
    volumes: "{{ prometheus_blackbox_docker_volumes }}"
    env_file: /etc/prometheus_blackbox_exporter/blackbox_exporter.env
    exposed_ports: "{{ prometheus_blackbox_ports|map(attribute='port') }}"
    published_ports: "{{ prometheus_blackbox_docker_publish_ports | default([], true) }}"
    cleanup: yes
  when: prometheus_blackbox_run_dockerised
