---

# configuration tasks for flannel

- name: flannel | environment | create file
  template:
    src: flannel.env.j2
    dest: /etc/flannel/flannel.env
    owner: root
    group: flannel
    mode: "0640"


- name: flannel | service | create configuration
  template:
    src: flannel.service.j2
    dest: "/etc/systemd/system/{{ flannel_service_name }}.service"
    owner: root
    group: root
    mode: "0750"
