---
# tasks file for libvirt-server

#
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - main.yml

#
- block:
    - import_tasks: install.yaml
    - import_tasks: run.yaml
    - import_tasks: storage.yaml
    - import_tasks: networks.yaml
    - import_tasks: domains.yaml
  tags:
    - libvirt
    - libvirt-server
