---
# tasks for configuring mysql

- name: mysql | configuration | create my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    owner: "root"
    group: "{{ mysql_group_name }}"
    mode: "0640"

- name: mysql | configuration | create my.cnf.d
  file:
    name: /etc/my.cnf.d
    state: directory
    owner: root
    group: "{{ mysql_group_name }}"
    mode: "01640"

- name: mysql | configuration | create server.cnf
  template:
    src: server.cnf.j2
    dest: /etc/my.cnf.d/server.cnf
    owner: root
    group: "{{ mysql_group_name }}"
    mode: "0640"

