---

# consul tasks for gluster server

- name: prometheus node exporter | consul | create config
  copy:
    dest: /etc/consul/service.d/node_exporter.json
    owner: root
    group: consul
    mode: "0640"
    content: |-
        {
          "service": {
            "checks": [
              {
                "interval": "30s",
                "http": "http://127.0.0.1:9100/health",
                "timeout": "5s"
              }
            ],
            "id": "node-exporter",
            "name": "node-exporter",
            "port": 9100
          }
        }


