---
# tasks file for prometheus_node_exporter

- block:
    - import_tasks: pre_install.yaml
    - import_tasks: install.yaml
    - import_tasks: configure.yaml
    - import_tasks: run.yaml
    - include_tasks: consul.yml
      when: prometheus_node_exporter_announce_consul
      tags:
        - consul
  tags:
    - prometheus
    - node_exporter
