---
# tasks file for prometheus_node_exporter

- include: pre_install.yml
  tags:
    - prometheus
    - node_exporter

- include: install.yml
  when: not prometheus_node_exporter_run_dockerised
  tags:
    - prometheus
    - node_exporter

- include: configure.yml
  tags:
    - prometheus
    - node_exporter

- include: run.yml
  tags:
    - prometheus
    - node_exporter
