---
# install tasks for php

- name: php | packages | install
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ php_prefix }}"
    - "{{ php_prefix }}-php-fpm"
    - "{{ php_prefix }}-php-mysqlnd"
