---
# install tasks for php

- name: php | packages | install
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ [php_prefix] | zip_longest(php_packages,fillvalue=php_prefix) | list | map('join','-') | list + [php_prefix]}}"
