---
# pre-install tasks for ossec common

- name: ossec | groups | create
  group:
    name: "{{ item }}"
    state: present
    system: true
  with_items:
    - ossec
    - ossecr

- name: ossec | users | create
  user:
    name: "{{ item }}"
    state: present
    system: true
    group: "{{ item }}"
    shell: /sbin/nologin
    home: "{{ ossec_home_dir }}"
    createhome: false
  with_items:
    - ossec
    - ossecr

- name: ossec | repository | add
  yum_repository:
    name: ossec-atomic
    state: present
    description: CentOS / Red Hat Enterprise Linux $releasever - atomic/ossec
    mirrorlist: "{{ ossec_repository_mirrorlist }}"
    gpgkey: "{{ ossec_repository_key_url }}"
    gpgcheck: true
    repo_gpgcheck: false
    enabled: true
    sslverify: true
    includepkgs: "ossec* inotify-tools"
  when: ansible_pkg_mgr == 'yum'
  register: ossec_repo

- name: ossec | repository | accept key
  command: yum -q makecache -y --disablerepo=* --enablerepo=ossec-atomic
  when: ossec_repo.changed | default(false)
