---

# configuration tasks for certbot

- name: certbot | configuration | create directories
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: certbot
    mode: "01750"
  with_items:
    - /etc/letsencrypt/env
