---
# tasks file for rsyslog

- block:
    - import_tasks: pre_install.yaml
    - import_tasks: install.yaml
    - import_tasks: configure.yaml
    - import_tasks: run.yaml
  tags:
    - syslog
    - rsyslog
