---
# defaults file for docker

# Packages to install
docker_package_names:
  - "docker"
  - "docker-python"

# Name of docker service to run
docker_service_name: "docker"

# Name of docker group, and owning group of the docker socket
docker_group: "docker"

# Path to docker config dir
docker_config_dir: "/etc/{{ docker_service_name }}/"

# Path to docker env file (typically a sysconfig file on RH, default file on Debian)
docker_environment_file: "/etc/sysconfig/docker"

# Whether or not to enable and start the docker service.
# By default, this is done unless running in a container.
docker_run_services: ansible_virtualization_role != 'guest' or ansible_virtualization_type != 'docker'

# Config for docker daemon.
# Note this uses overlay2, which is not necessarily suitable for
# production, notably on centos.
docker_default_config:
  hosts:
    - unix:///var/run/docker.sock
  "storage-driver": "overlay2"
  group: "{{ docker_group }}"
  "storage-opts":
    - "overlay2.override_kernel_check=true"
  "metrics-addr" : "0.0.0.0:9323"
  "experimental" : true

docker_config: "{{ docker_default_config }}"

docker_use_flannel_network: false

# The docker default bridge IP.
docker_bip: 172.17.0.1/16

# Container network MTU
docker_mtu: 1420

# Enable/disable IP masquerading
docker_ipmasq: true
