---
# Channel management tasks for rocket.chat

- name: rocket.chat | api | create {{ channel.name }} channel
  uri:
    url: "{{ rocketchat_root_url }}/api/v1/channels.create"
    method: POST
    body_format: json
    return_content: true
    body:
      name: "{{ channel.name }}"
      members: "{{ channel.members | default([]) }}"
      readOnly: "{{ channel.readOnly | default(false, true) | lower }}"
    headers:
      X-Auth-Token: "{{ rocketchat_token.json.data.authToken }}"
      X-User-Id: "{{ rocketchat_token.json.data.userId }}"
  when: channel.action | default("none") == "create"
  register: channel_info
  failed_when: not channel_info.json.success and not channel_info.json.get("errorType") == "error-duplicate-channel-name"

- name: rocket.chat | api | get channel info for {{ channel.name }}
  uri:
    url: '{{ rocketchat_root_url }}/api/v1/channels.list?query={"name":"{{ channel.name }}"}'
    method: GET
    return_content: true
    headers:
      X-Auth-Token: "{{ rocketchat_token.json.data.authToken }}"
      X-User-Id: "{{ rocketchat_token.json.data.userId }}"
    status_code: 200
  when: channel.action | default("none") != "create"
  register: channel_info

# rocketchat doesn't yet support clearing a channel other than via the API.
# https://github.com/RocketChat/Rocket.Chat/issues/2355
- name: rocket.chat | api | clear channel history
  uri:
    url: "{{ rocketchat_root_url }}/api/v1/channels.cleanHistory"
    method: POST
    body_format: json
    body:
      roomId: "{{ channel.channel_id | default(channel_info.json.channels[0]._id) }}"
      latest: "{{ channel.clear_latest | default(channel_info.json.channels[0]._updatedAt) }}"
      oldest: "{{ channel.clear_oldest | default(channel_info.json.channels[0].ts) }}"
      inclusive: "{{ channel.clear_inclusive | default(false, true) }}"
    headers:
      X-Auth-Token: "{{ rocketchat_token.json.data.authToken }}"
      X-User-Id: "{{ rocketchat_token.json.data.userId }}"
    status_code: 200
  when: channel.action | default("none") == "clear"
