---
# tasks file for rocket.chat

- block:
    - import_tasks: pre_install.yml
    - import_tasks: install.yml
    - import_tasks: configure.yml
    - import_tasks: run.yml
  tags:
    - rocketchat

- import_tasks: bot.yml
  when: rocketchat_install_bot
  tags:
    - rocketchat
    - hubot
