---
# tasks for configuring prometheus

- name: prometheus | configuration | create prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: prometheus
    mode: "0640"

- name: prometheus | environment | create env file for systemd unit
  copy:
    dest: /etc/sysconfig/prometheus
    content: OPTIONS="-web.listen-address=':{{ (prometheus_ports[0]|string).split(':')[0] }}'"
    owner: root
    group: prometheus
    mode: "0640"
    force: no

