---
# tasks for configuring prometheus

- name: prometheus | configuration | create prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: root
    group: prometheus
    mode: "0640"
    validate: /opt/prometheus/current/promtool check-config %s

- name: prometheus | environment | create env file for systemd unit
  copy:
    dest: /etc/sysconfig/prometheus
    content: OPTIONS="-web.listen-address=':{{ (prometheus_ports[0]|string).split(':')[0] }}' -config.file=/etc/prometheus/prometheus.yml"
    owner: root
    group: prometheus
    mode: "0640"
    force: no

- name: prometheus | scrape targets | create directories
  file:
    name: "/etc/prometheus/targets.d/{{ item }}"
    state: directory
    owner: root
    group: prometheus
    mode: "01750"
  with_items: "{{ prometheus_scrape_targets | map(attribute='type') | list | unique }}"

- name: prometheus | scrape targets | configure
  template:
    src: scrape_targets.json.j2
    dest: "/etc/prometheus/targets.d/{{ item.type }}/{{ item.name }}.json"
    owner: root
    group: prometheus
    mode: "0640"
  with_items: "{{ prometheus_scrape_targets }}"
