---
# tasks file for prometheus


- import_tasks: pre_install.yml
  tags:
    - prometheus

- import_tasks: install.yml
  tags:
    - prometheus
  when: not prometheus_run_dockerised

- import_tasks: configure.yml
  tags:
    - prometheus

#- import_tasks: rules.yml
#  tags:
#    - prometheus
#    - alertmanager
#    - rules

- import_tasks: run.yml
  tags:
    - prometheus
