---

# Tasks to setup environment for prometheus

- name: prometheus | group | create
  group:
    name: prometheus
    state: present
    system: yes

- name: prometheus | user | create
  user:
    name: prometheus
    state: present
    group: prometheus
    shell: /sbin/nologin
    home: /opt/prometheus
    expires: -1
    system: yes

- name: prometheus | directories | create
  file:
    name: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: "01750"
  with_items:
    - /etc/prometheus
    - /opt/prometheus/data
    - /opt/prometheus/logs
    - /opt/prometheus/releases
