---
# Tasks for configuring firewalld - these assume it is running

# Default target for most zones is REJECT - DROP is preferrable.
# Three zones have their own explicit target, which remains unchanged:
# * drop zone will DROP
# * trusted zone will ACCEPT
# * block zone will REJECT
- name: firewalld | configuration | set default target to DROP
  command: "firewall-cmd --set-target=DROP --zone={{ item }} --permanent"
  vars:
    creates: "/etc/firewalld/zones/{{ item }}.xml"
  with_items:
    - work
    - internal
    - external
    - home
    - dmz
    - public

- name: firewalld | configuration | create zone config
  template:
    src: zone.xml.j2
    dest: "/etc/firewalld/zones/{{ item.name }}.xml"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ firewalld_zones }}"
  notify:
    - firewalld | service | restart
# Create direct rules

- name: firewalld | configuration | create direct rules
  template:
    src: direct.xml.j2
    dest: /etc/firewalld/direct.xml
    owner: root
    group: root
    mode: 0640
