---

# installation tasks for firewalld role

- name: firewalld | package | install
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ firewalld_package_names }}"
  tags:
    - firewalld
