---
# tasks file for firewalld


- block:
    - import_tasks: pre_install.yml
    - import_tasks: install.yml
    - import_tasks: configure.yml
    - import_tasks: run.yml
  tags:
    - firewalld

# Ensure firewalld's handlers are flushed, to try and ensure firewalld
# is running and has the expected/desired rules active.
- meta: flush_handlers
  tags:
    - firewalld
