---

# pre-install tasks for firewalld

- name: firewalld | directories | create configuration directories
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "01750"
  with_items:
    - /etc/firewalld
