---
# tasks file for pam

#
- name: pam | expiration | configure maximum inactivity
  lineinfile:
    path: /etc/default/useradd
    regexp: INACTIVE=\d+
    line: "INACTIVE={{pam_max_inactive}}"
    create: yes
    owner: root
    group: root
    mode: "0640"
  tags:
    - pam

- import_tasks: system.yml
  tags:
    - pam
    - system
    - password_quality
    - hardening

- import_tasks: smartcard.yml
  tags:
    - pam
    - system
    - smartcard
    - hardening


