---

# Task for PAM to use smartcards

- name: pam | smartcard | install pam_pkcs11 and esc
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - pam_pkcs11
    - esc

- name: pam | smartcard | create smartcard-auth config
  template:
    src: smartcard-auth.j2
    dest: "{{ item }}"
    owner: root
    group: root
    mode: "0640"
  with_items:
    - /etc/pam.d/smartcard-auth
    - /etc/pam.d/smartcard-auth-ac

- name: pam | smartcard | create pam_pkcs11.conf
  template:
    src: pam_pkcs11.conf.j2
    dest: /etc/pam_pkcs11/pam_pkcs11.conf
    owner: root
    group: root
    mode: "0640"

- name: pam | smartcard | enable PC/SC smart card service
  service:
    name: pcscd
    state: started
    enabled: yes
  when: pam_run_services
