---
# tasks for runnning alertmanager

- name: prometheus alertmanager | service | create unit file
  template:
    src: prometheus_alertmanager.service.j2
    dest: /etc/systemd/system/prometheus_alertmanager.service
    owner: root
    group: root
    mode: "0640"

- name: prometheus alertmanager | service | enable and run
  service:
    name: prometheus_alertmanager.service
    state: started
    enabled: yes
