---
# pre-install tasks for cfssl

- name: cfssl | create | group
  group:
    name: cfssl
    state: present

- name: cfssl | create | user
  user:
    name: cfssl
    state: present
    group: cfssl
    shell: /sbin/nologin
    home: /var/lib/cfssl

- name: cfssl | create | directories
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: cfssl
    mode: "01755"
  with_items:
    - /etc/cfssl
    - /etc/cfssl/env.d
    - /etc/cfssl/conf.d
    - /etc/cfssl/request.d
    - /etc/cfssl/response.d

- name: cfssl | create | response directories
  file:
    name: "/etc/cfssl/response.d/{{ item.name }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: root
    mode: "01700"
  when: not item.output_directory | default(false, true)
  with_items: "{{ cfssl_requests }}"
