---
# install tasks for consul

- name: consul | binary | download
  get_url:
    url: "{{ consul_url }}"
    checksum: "{{ consul_checksums[('_').join([consul_platform, consul_architecture])] }}"
    owner: consul
    group: consul
    mode: "0640"
    dest: "{{ consul_home }}/releases/consul_{{consul_version}}.zip"
  register: consul_downloaded

- name: consul | binary | extract
  unarchive:
    src: "{{ consul_home }}/releases/consul_{{consul_version}}.zip"
    dest: "/usr/local/bin"
    owner: root
    group: consul
    mode: "0550"
    remote_src: true
  when: consul_downloaded.changed
  notify:
    - consul | service | restart
