---
# tasks for hardenin system's security limits

- name: os hardening | limits | create main limits.conf
  template:
    src: limits.conf.j2
    dest: /etc/security/limits.conf
    owner: root
    group: root
    mode: "0600"

