---
# tasks file for os-hardening

# Try and ensure the package manager installs sane things before starting.
- include: yum.yml
  when: "ansible_pkg_mgr == 'yum'"
  tags:
    - os_hardening
    - selinux

- include: grub.yml
  tags:
    - os_hardening
    - grub
    - bootloader

- include: selinux.yml
  when: "os_hardening_mac == 'selinux'"
  tags:
    - os_hardening
    - selinux

- include: tcp_wrappers.yml
  tags:
    - os_hardening
    - network
    - tcp_wrappers

- include: prelink.yml
  tags:
    - os_hardening
    - prelink

- include: modprobe.yml
  tags:
    - os_hardening
    - modprobe
    
- include: sysctl.yml
  tags:
    - os_hardening
    - sysctl

- include: removal.yml
  tags:
    - os_hardening
    - removal

- include: aide.yml
  when: "os_hardening_integrity == 'aide'"
  tags:
    - os_hardening
    - integrity
    - aide

