---
# task file for selinux-related OS hardening

- name: os hardening | selinux | install
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - selinux
    - python-selinux

- name: os hardening | selinux | set enforcing
  selinux:
    name: selinux
    policy: "{{ os_hardening_selinux_policy }}"
    state: enforcing
