---
# task file for selinux-related OS hardening

- name: os hardening | selinux | install
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux
    - container-selinux
    # Needed for ansible to speak to selinux
    - policycoreutils-python

- name: os hardening | selinux | set enforcing
  selinux:
    state: enforcing
    policy: "{{ os_hardening_selinux_policy }}"
