---

# tasks to ensure system accounts cannot be logged in to

- name: os hardening | system accounts | collect
  command: cat /etc/passwd
  register: os_hardening_passwd_entries

- name: os hardening | system accounts | set shell to /sbin/nologin
  user:
    name: "{{ item.split(':',2)[0] }}"
    state: present
    shell: /sbin/nologin
  when: item.split(':')[2]|int < 1000 and item.split(':')[2]|int > 0
  with_items: "{{ os_hardening_passwd_entries.stdout_lines }}"
